################################################################################
#                 Continuous Integration Control for Travis CI                 #
#                                                                              #
# This file controls the build and test process run on Travis CI on every push #
# to the master branch. It runs the test suite and then produces a tarpaulin   #
# coverage report.                                                             #
################################################################################

os: linux
language: rust
cache: cargo
jobs:
  include:
    # Disable cross while building coverage, since cross interferes
    # with caching and the current tarpaulin install.
    - rust: stable
      env: TARGET=x86_64-unknown-linux-gnu COVERAGE=1 DISABLE_CROSS=1
    - rust: beta
      env: TARGET=x86_64-unknown-linux-gnu
    - rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu

    # Android
    - env: TARGET=aarch64-linux-android DISABLE_TESTS=1
    - env: TARGET=arm-linux-androideabi DISABLE_TESTS=1
    - env: TARGET=armv7-linux-androideabi DISABLE_TESTS=1
    - env: TARGET=i686-linux-android DISABLE_TESTS=1
    - env: TARGET=x86_64-linux-android DISABLE_TESTS=1

    # iOS
    - env: TARGET=aarch64-apple-ios DISABLE_TESTS=1
      os: osx
    - env: TARGET=x86_64-apple-ios DISABLE_TESTS=1
      os: osx

    # Linux
    - env: TARGET=aarch64-unknown-linux-gnu
    - env: TARGET=arm-unknown-linux-gnueabi
    - env: TARGET=armv7-unknown-linux-gnueabihf
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=i686-unknown-linux-musl
    - env: TARGET=mips-unknown-linux-gnu
    - env: TARGET=mips64-unknown-linux-gnuabi64
    - env: TARGET=mips64el-unknown-linux-gnuabi64
    - env: TARGET=mipsel-unknown-linux-gnu
    - env: TARGET=powerpc-unknown-linux-gnu
    - env: TARGET=powerpc64le-unknown-linux-gnu
    - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-linux-musl

    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # *BSD
    - env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1

    # Windows
    - env: TARGET=x86_64-pc-windows-gnu
  allow_failures:
    - rust: nightly

    # Targets not available on current MSRV. Continue testing in the event that
    # they become available in the future.

    # iOS
    - env: TARGET=armv7-apple-ios DISABLE_TESTS=1
      os: osx
      rust: stable
    - env: TARGET=armv7s-apple-ios DISABLE_TESTS=1
      os: osx
      rust: stable
    - env: TARGET=i386-apple-ios DISABLE_TESTS=1
      os: osx
      rust: stable


dist: trusty
addons:
  apt:
    packages:
      - libssl-dev

before_cache:
  - bash ci/install_tarpaulin.sh

before_install:
  - set -e
  - rustup self update

install:
  - bash ci/install_rust.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_success:
  - bash ci/coverage.sh
