################################################################################
#                              Book Configuration                              #
#                                                                              #
# This file configures the `mdbook` executable used to compile `book/` into a  #
# project manual.                                                              #
################################################################################

[book]
title = "A Userâ€™s Guide to the `bitvec` Project"
authors = [
	"myrrlyn <self@myrrlyn.dev>",
]
description = "A more thorough manual of the `bitvec` project"
src = "book"

[build]
build-dir = "target/book"

[output.html]
mathjax-support = true

[output.html.playpen]
line-numbers = true
