########################################################################
#                       Rust Style Configuration                       #
#                                                                      #
# This file controls the operation of `rustfmt` and `cargo fmt`. As    #
# the `rustfmt` tool still has many unstable options, this file is     #
# only usable by the nightly release of Rust at least as of the date   #
# this file was last touched.                                          #
#                                                                      #
# See <https://rust-lang.github.io/rustfmt/?version=v1.5.1>           #
########################################################################

# Stable as of current nightly
# array_width = 60                   # Leave implicit
# attr_fn_like_width = 70            # Leave implicit
# chain_width = 60                   # Leave implicit
edition = "2018"
fn_args_layout = "Tall"
# fn_call_width = 60                 # Leave implicit
force_explicit_abi = true
hard_tabs = true
match_arm_leading_pipes = "Never"
max_width = 81
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
# single_line_if_else_max_width = 50 # Leave implicit
# struct_lit_width = 18              # Leave implicit
# struct_variant_width = 35          # Leave implicit
tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true

# Still unstable
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
color = "Auto"
combine_control_expr = true
comment_width = 80
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
disable_all_formatting = false
empty_item_single_line = true
enum_discrim_align_threshold = 40
error_on_line_overflow = false
error_on_unformatted = true
fn_single_line = false
force_multiline_blocks = false
format_code_in_doc_comments = false
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
group_imports = "StdExternalCrate"
hide_parse_errors = false
ignore = []
imports_indent = "Block"
imports_granularity = "Crate"
imports_layout = "Vertical"
indent_style = "Block"
inline_attribute_width = 0
match_arm_blocks = true
match_block_trailing_comma = true
# merge_imports = true # Deprecated
normalize_comments = false
normalize_doc_attributes = false
overflow_delimited_expr = true
reorder_impl_items = true
required_version = "1.5.1"
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = true
struct_field_align_threshold = 8
struct_lit_single_line = true
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = true
version = "Two"
where_single_line = true
wrap_comments = true
